language: python

python:
  - "3.5"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get update
  - bash ./scripts/init_and_wait_for_db.sh

install:
  - cp faf-server.example.pem faf-server.pem
  - docker build -t faf-server .

script:
  - docker run --link faf-db:db -e FAF_DB_PASSWORD=banana -e COVERALLS_REPO_TOKEN=Vl36DD3XeJI1KjzoyGgxpV3wsVohnJW22 faf-server bash scripts/run_and_report_coverage.sh
