language: python

python:
  - "3.4"

install:
  - cp passwords.py.example passwords.py
  - sudo apt-get install libqt4-dev
  - pip install PySide --no-index --find-links=http://content.dev.faforever.com/wheel/ --trusted-host content.dev.faforever.com
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
  - "pip install pytest pytest-qt pytest-cov python-coveralls configobj mock quamash pygeoip trueskill pyflakes ujson aiomysql steamodd"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mysql -e 'create database faf_test;'"

script:
  - pip install -e .
  - export QUAMASH_QTIMPL=PySide
  - py.test --slow --cov-report term-missing --cov=server --cov=updater
  - pyflakes . || true

after_success:
  - coveralls
