language: python

python:
  - "3.5"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo apt-get update
  - pushd db
  - docker build -t faf-db .
  - docker run -d --name faf-db -e MYSQL_ROOT_PASSWORD=banana -p 3306:3306 faf-db
  - until docker exec -i faf-db ./healthcheck.sh 2>/dev/null; do sleep 1; done
  - docker exec -i faf-db mysql -uroot -pbanana faf < test-data.sql
  - popd
  - python -m pip install coveralls

install:
  - cp faf-server.example.pem faf-server.pem
  - docker build -t faf-server .

script:
  - docker run --name faf-server --link faf-db:db -e FAF_DB_PASSWORD=banana -e FAF_DB_NAME=faf faf-server bash scripts/run_tests_with_coverage.sh
  - docker cp faf-server:/code/.coverage .coverage
  - sed -i.bak s#/code/#$(pwd)/#g .coverage
  - coveralls

after_success:
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
      docker push faforever/faf-python-server;
    fi
