language: python

python:
  - "3.5"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get update
  - bash ./scripts/init_and_wait_for_db.sh

install:
  - docker build -t faf-server .

script:
  - docker run --link faf-db:db -e FAF_DB_PASSWORD=banana faf-server py.test --cov-report term-missing --cov=server
  - pyflakes . || true

after_success:
  # TODO: Add missing -e COVERALLS_REPO_TOKEN
  # however, coveralls is currently offline, so I can't fetch it.
  - docker run faf-server coveralls
