language: python

python:
  - "3.5"

install:
  - cp faf-server.example.pem faf-server.pem
  - "pip install --upgrade pip"
  - "pip install --use-wheel --trusted-host content.dev.faforever.com -r requirements.txt"

before_script:
  - "mysql -e 'create database faf_test;'"

script:
  - pip install -e .
  - export FAF_DB_PASSWORD=
  - py.test --cov-report term-missing --cov=server
  - pyflakes . || true

after_success:
  - coveralls
